name: Release

permissions:
  contents: write

on:
  push:
    tags: [ "release-*" ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build custom iosevka fonts
        uses: addnab/docker-run-action@v3
        with:
          image: avivace/iosevka-build:latest
          options: -v ${{github.workspace}}:/build
          run: /bin/bash /run.sh

      - name: Zip files
        run: zip -r iosevka-comfy.zip ${{github.workspace}}/dist/iosevka-comfy

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: iosevka-comfy
          path: iosevka-comfy.zip

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: iosevka-comfy

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            iosevka-comfy.zip
